name: Build And Release with CMake
run-name: Auto Release for TAG ${{ github.ref_name }}
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up MS Build
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v2
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
      - name: Set up CMake
        uses: threeal/cmake-action@main
        with:
          run-build: true
          options: |
            CMAKE_BUILD_TYPE=Release
          generator: Ninja
      - name: Make dist folder (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p dist/dynamic/
          mkdir -p dist/static/
          cp build/libOpenEStimCtrl.so dist/dynamic/
          cp build/library_static/* dist/static/
          mkdir releases
      - name: Make dist folder (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p dist/dynamic/
          mkdir -p dist/static/
          cp build/libOpenEStimCtrl.dylib dist/dynamic/
          cp build/library_static/* dist/static/
          mkdir releases
      - name: Make dist folder (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          ls build
          mkdir dist
          cp build/Release/* dist/
          cp build/library_static/* dist/
          mkdir releases
      - name: Zipped dist folder (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path dist/* -Destination releases/OpenEStimCtrl-${{ runner.os }}-${{ runner.arch }}-$env:GITHUB_REF_NAME.zip
      - name: Tar and Gzip dist folder (Linux and MacOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: tar -czvf releases/OpenEStimCtrl-${{ runner.os }}-${{ runner.arch }}-$GITHUB_REF_NAME.tar.gz dist/*
      - name: Upload Release Asset
        uses: ncipollo/release-action@v1
        if: ${{ success() }}
        with:
          allowUpdates: true
          artifacts: 'releases/*'
          makeLatest: true
